### ISSUE TITLE
Fails to run vite

### ISSUE THREAD

**Issue by eviweb** [innocenzi/laravel-vite#291]
Hi,
with the current version `0.2.0-beta.25`, I encounter the following error while launching `vite` using `npm run dev`:
```
failed to load config from /path/to/my/project/vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/my/project/node_modules/chalk/source/index.js from /path/to/my/project/node_modules/vite-plugin-laravel/dist/index.cjs not supported.
Instead change the require of index.js in /path/to/my/project/node_modules/vite-plugin-laravel/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/path/to/my/project/node_modules/vite-plugin-laravel/dist/index.cjs:10:11)
    at Object.<anonymous> (/path/to/my/project/vite.config.ts:29:42)
    at Object.require.extensions.<computed> [as .ts] (/path/to/my/project/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61998:20)
    at loadConfigFromBundledFile (/path/to/my/project/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:62006:17)
    at loadConfigFromFile (/path/to/my/project/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61925:32)
    at async resolveConfig (/path/to/my/project/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61450:28)
    at async createServer (/path/to/my/project/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:60105:20)
    at async CAC.<anonymous> (/path/to/my/project/node_modules/vite/dist/node/cli.js:688:24)
```
 This seems to come from chalk version `5.0.1`.
On fixing this error: [https://bobbyhadz.com/blog/javascript-error-err-require-esm-require-of-es-module-not-supported](https://bobbyhadz.com/blog/javascript-error-err-require-esm-require-of-es-module-not-supported)
On fixing chalk issue: [https://bobbyhadz.com/blog/javascript-chalk-error-err-require-esm-of-es-module](https://bobbyhadz.com/blog/javascript-chalk-error-err-require-esm-of-es-module)

Hope that's help,

**Comment by innocenzi** [comment]
Thanks, I fixed it in https://github.com/innocenzi/laravel-vite/commit/545db6d9ef3e253af477a4b918935b455a55338a. I knew about this issue, but `pnpm` overrides didn't work because they should be in the root `package.json`, so last time I updated deps chalk got bumped. Thanks for the report!

**Comment by eviweb** [comment]
@innocenzi 
in fact the problem persists, I think the cause is here:  https://github.com/innocenzi/laravel-vite/blob/22d8d8dd8e6b217ed8355eaf8c1214d3f652d135/vite-plugin-laravel/package.json#L44

**Comment by innocenzi** [comment]
I guess the `require` will take the first version in the dependency tree... that's unfortunate, I'll just have to use explicit versions like before and be careful when bumping them

Bad move on sindresorhus for not providing cjs bundles, makes everyone's life a bit harder :(

**Comment by eviweb** [comment]
It works, thanks.
